name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Install Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: 1
    - run: julia -e '
            using Pkg;
            Pkg.add(Pkg.PackageSpec(name="NodeJS"));
            using NodeJS;
            Pkg.activate("."); Pkg.instantiate();
            Pkg.add(Pkg.PackageSpec(name="Franklin", rev="master"));
            using Franklin;
            optimize(minify=false, prerender=false);'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: __site